In [1]:
# Input file (already renamed)
input_file = "names.txt"

# Output file to save cleaned names
output_file = "cleaned_names.txt"

# Process the file
with open(input_file, "r") as infile, open(output_file, "w") as outfile:
    names = set()  # Use a set to remove duplicates
    for line in infile:
        # Split by commas and extract the name (first column)
        name = line.split(",")[0]
        # Convert to lowercase and strip extra spaces
        names.add(name.strip().lower())

    # Write the cleaned names to the new file (no numbering)
    for name in sorted(names):  # Optional: Sort names alphabetically
        outfile.write(f"{name}\n")  # Write each name on a new line

print(f"Cleaned {len(names)} unique names and saved to {output_file}.")


Cleaned 29681 unique names and saved to cleaned_names.txt.


In [2]:
words = open('cleaned_names.txt', 'r').read().splitlines()

In [3]:
words[:10]

['aaban',
 'aabid',
 'aabidah',
 'aabir',
 'aabriella',
 'aada',
 'aadam',
 'aadarsh',
 'aadaya',
 'aaden']

In [4]:
len(words)

29681

In [5]:
min(len(w) for w in words)

2

In [6]:
max(len(w) for w in words)

15

In [7]:
b = {}
for w in words:
  chs = ['<S>'] + list(w) + ['</E>']
  for ch1, ch2 in zip(chs, chs[1:]):
    bigram = (ch1, ch2)
    b[bigram] = b.get(bigram, 0) + 1
    # print(ch1, ch2)

In [8]:
# counts of all the words
b

{('<S>', 'a'): 4155,
 ('a', 'a'): 547,
 ('a', 'b'): 531,
 ('b', 'a'): 302,
 ('a', 'n'): 5120,
 ('n', '</E>'): 6040,
 ('b', 'i'): 198,
 ('i', 'd'): 408,
 ('d', '</E>'): 488,
 ('d', 'a'): 1226,
 ('a', 'h'): 2258,
 ('h', '</E>'): 2318,
 ('i', 'r'): 816,
 ('r', '</E>'): 1232,
 ('b', 'r'): 750,
 ('r', 'i'): 2785,
 ('i', 'e'): 1546,
 ('e', 'l'): 3093,
 ('l', 'l'): 1273,
 ('l', 'a'): 2482,
 ('a', '</E>'): 6508,
 ('a', 'd'): 977,
 ('a', 'm'): 1512,
 ('m', '</E>'): 479,
 ('a', 'r'): 3030,
 ('r', 's'): 167,
 ('s', 'h'): 1230,
 ('a', 'y'): 1904,
 ('y', 'a'): 2088,
 ('d', 'e'): 1169,
 ('e', 'n'): 2417,
 ('d', 'h'): 116,
 ('h', 'a'): 2112,
 ('a', 'v'): 789,
 ('v', '</E>'): 86,
 ('v', 'a'): 614,
 ('h', 'i'): 704,
 ('i', '</E>'): 2233,
 ('r', 'a'): 2247,
 ('h', 'v'): 39,
 ('v', 'i'): 880,
 ('i', 'k'): 425,
 ('k', '</E>'): 356,
 ('k', 'a'): 1607,
 ('h', 'y'): 191,
 ('r', 'e'): 1553,
 ('e', 'd'): 363,
 ('d', 'd'): 138,
 ('d', 'y'): 268,
 ('y', '</E>'): 1737,
 ('a', 's'): 1053,
 ('s', 'r'): 55,
 ('d', '

In [9]:
sorted(b.items(), key = lambda kv: -kv[1])

[(('a', '</E>'), 6508),
 (('n', '</E>'), 6040),
 (('a', 'n'), 5120),
 (('<S>', 'a'), 4155),
 (('e', '</E>'), 3676),
 (('e', 'l'), 3093),
 (('a', 'r'), 3030),
 (('n', 'a'), 2923),
 (('r', 'i'), 2785),
 (('<S>', 'k'), 2700),
 (('l', 'e'), 2688),
 (('l', 'a'), 2482),
 (('m', 'a'), 2451),
 (('a', 'l'), 2431),
 (('e', 'n'), 2417),
 (('<S>', 'm'), 2401),
 (('l', 'i'), 2361),
 (('i', 'a'), 2347),
 (('h', '</E>'), 2318),
 (('a', 'h'), 2258),
 (('r', 'a'), 2247),
 (('<S>', 'j'), 2239),
 (('i', '</E>'), 2233),
 (('o', 'n'), 2213),
 (('h', 'a'), 2112),
 (('y', 'a'), 2088),
 (('i', 'n'), 1963),
 (('<S>', 's'), 1914),
 (('a', 'y'), 1904),
 (('n', 'n'), 1818),
 (('e', 'r'), 1772),
 (('y', '</E>'), 1737),
 (('y', 'n'), 1641),
 (('k', 'a'), 1607),
 (('n', 'i'), 1607),
 (('<S>', 'd'), 1579),
 (('r', 'e'), 1553),
 (('a', 'i'), 1552),
 (('i', 'e'), 1546),
 (('a', 'm'), 1512),
 (('l', 'y'), 1487),
 (('<S>', 'r'), 1471),
 (('<S>', 'l'), 1451),
 (('<S>', 'e'), 1435),
 (('<S>', 'c'), 1398),
 (('j', 'a'), 138

In [10]:
list(w)

['z', 'z', 'y', 'z', 'x']

In [11]:
w

'zzyzx'

In [12]:
w[1:]

'zyzx'

In [13]:
# storing the information in 2d array - rows = 1st charachter, columns = 2nd charachter
import torch

In [14]:
a = torch.zeros((3, 5), dtype = torch.int32)
a

tensor([[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]], dtype=torch.int32)

In [15]:
a.dtype

torch.int32

In [16]:
# changing bit in the array
a[1, 3] = 1
a

tensor([[0, 0, 0, 0, 0],
        [0, 0, 0, 1, 0],
        [0, 0, 0, 0, 0]], dtype=torch.int32)

In [17]:
N = torch.zeros((27, 27), dtype = torch.int32)

In [18]:
len(set(''.join(words)))

26

In [19]:
chars = sorted(list(set(''.join(words))))
stoi = {s:i+1 for i, s in enumerate(chars)}
stoi['.'] = 0
itos = {i:s for s, i in stoi.items()}

In [20]:
 # stoi

In [21]:
for w in words:
  chs = ['.'] + list(w) + ['.']
  for ch1, ch2 in zip(chs, chs[1:]):
    ix1 = stoi[ch1]
    ix2 = stoi[ch2]
    N[ix1, ix2] += 1

In [22]:
import matplotlib.pyplot as plt
%matplotlib inline

plt.figure(figsize=(16, 16))
plt.imshow(N, cmap='Blues')

for i in range(27):
  for j in range(27):
    chstr = itos[i] + itos[j]
    plt.text(j, i, chstr, ha='center', va='bottom', color= 'gray')
    plt.text(j, i, N[i, j].item(), ha='center', va='top', color= 'gray')
plt.axis('off')
plt.tight_layout()
plt.show()

: 

In [22]:
N[0, :]

tensor([   0, 4155, 1153, 1398, 1579, 1435,  383,  620,  798,  553, 2239, 2700,
        1451, 2401, 1090,  358,  467,   85, 1471, 1914, 1209,   71,  363,  262,
         131,  519,  876], dtype=torch.int32)

In [23]:
# creating probability vector
p = N[0].float()
p = p / p.sum()
p

tensor([0.0000, 0.1400, 0.0388, 0.0471, 0.0532, 0.0483, 0.0129, 0.0209, 0.0269,
        0.0186, 0.0754, 0.0910, 0.0489, 0.0809, 0.0367, 0.0121, 0.0157, 0.0029,
        0.0496, 0.0645, 0.0407, 0.0024, 0.0122, 0.0088, 0.0044, 0.0175, 0.0295])

In [24]:
p.sum()

tensor(1.0000)

In [25]:
g = torch.Generator().manual_seed(2147483647)
ix = torch.multinomial(p, num_samples=1, replacement=True, generator=g).item()
itos[ix]

'j'

In [26]:
g = torch.Generator().manual_seed(2147483647)
p = torch.rand(3, generator=g)
p = p / p.sum()
p

tensor([0.6064, 0.3033, 0.0903])

In [27]:
torch.multinomial(p, num_samples=100, replacement=True, generator=g)

tensor([1, 1, 2, 0, 0, 2, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 2, 0, 0,
        1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1,
        0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
        0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 2, 0, 0, 0, 0, 0, 0, 1, 0, 0, 2, 0, 1, 0,
        0, 1, 1, 1])

In [28]:
p.shape

torch.Size([3])

In [41]:
P.shape

torch.Size([27, 27])

In [ ]:
# 27, 27
# 27, 1

In [51]:
P.sum(1, keepdim=True).shape

torch.Size([27, 1])

In [50]:
P = N.float()
P /= P.sum(1, keepdims=True)

In [48]:
P[:,0].sum()

tensor(2.9735)

### Note: Broadcasting Sementics from Pytorch or tutorials and practice 

In [57]:
g = torch.Generator().manual_seed(2147483647)

for i in range(5):

  out = []
  ix = 0
  while True:
    p = P[ix]
    # p = N[ix].float()
    # p = p / p.sum()
    # p = torch.ones(27) / 27.0
    ix = torch.multinomial(p, num_samples=1, replacement=True, generator=g).item()
    out.append(itos[ix])
    if ix == 0:
      break
  print(''.join(out))


junide.
janasah.
p.
cony.
a.


In [ ]:
# log(a+b+c) = log(a) + log(b) + log(c)

In [ ]:
# GOAL: 

In [63]:
log_likelihood = 0.0
n = 0

for w in words[:3]:
  chs = ['.'] + list(w) + ['.']
  for ch1, ch2 in zip(chs, chs[1:]):
    ix1 = stoi[ch1]
    ix2 = stoi[ch2]
    prob = P[ix1, ix2]
    logprob = torch.log(prob)
    log_likelihood += logprob
    n += 1
    print(f'{ch1}{ch2}: {prob:.4f} {logprob:4f}') # probabilities model assigns to the bigrams

print(f'{log_likelihood=}')
nll = -log_likelihood
print(f'{nll=}') 
print(f'{nll/n=}') # average negative log likelihood

.a: 0.1400 -1.966195
aa: 0.0170 -4.075490
ab: 0.0165 -4.105177
ba: 0.1242 -2.086042
an: 0.1590 -1.839029
n.: 0.3552 -1.035162
.a: 0.1400 -1.966195
aa: 0.0170 -4.075490
ab: 0.0165 -4.105177
bi: 0.0814 -2.508202
id: 0.0245 -3.707696
d.: 0.0956 -2.347465
.a: 0.1400 -1.966195
aa: 0.0170 -4.075490
ab: 0.0165 -4.105177
bi: 0.0814 -2.508202
id: 0.0245 -3.707696
da: 0.2402 -1.426268
ah: 0.0701 -2.657704
h.: 0.3207 -1.137119
log_likelihood=tensor(-55.4012)
nll=tensor(55.4012)
nll/n=tensor(2.7701)


### Note: to see the literature of Maximum likelihood estimation
* WolframAlpha website for logs