In [1]:
# Input file (already renamed)
input_file = "names.txt"

# Output file to save cleaned names
output_file = "cleaned_names.txt"

# Process the file
with open(input_file, "r") as infile, open(output_file, "w") as outfile:
    names = set()  # Use a set to remove duplicates
    for line in infile:
        # Split by commas and extract the name (first column)
        name = line.split(",")[0]
        # Convert to lowercase and strip extra spaces
        names.add(name.strip().lower())

    # Write the cleaned names to the new file (no numbering)
    for name in sorted(names):  # Optional: Sort names alphabetically
        outfile.write(f"{name}\n")  # Write each name on a new line

print(f"Cleaned {len(names)} unique names and saved to {output_file}.")


Cleaned 29681 unique names and saved to cleaned_names.txt.


In [2]:
words = open('cleaned_names.txt', 'r').read().splitlines()

In [3]:
words[:10]

['aaban',
 'aabid',
 'aabidah',
 'aabir',
 'aabriella',
 'aada',
 'aadam',
 'aadarsh',
 'aadaya',
 'aaden']

In [4]:
len(words)

29681

In [5]:
min(len(w) for w in words)

2

In [6]:
max(len(w) for w in words)

15

In [7]:
b = {}
for w in words:
  chs = ['<S>'] + list(w) + ['</E>']
  for ch1, ch2 in zip(chs, chs[1:]):
    bigram = (ch1, ch2)
    b[bigram] = b.get(bigram, 0) + 1
    # print(ch1, ch2)

In [8]:
# counts of all the words
b

{('<S>', 'a'): 4155,
 ('a', 'a'): 547,
 ('a', 'b'): 531,
 ('b', 'a'): 302,
 ('a', 'n'): 5120,
 ('n', '</E>'): 6040,
 ('b', 'i'): 198,
 ('i', 'd'): 408,
 ('d', '</E>'): 488,
 ('d', 'a'): 1226,
 ('a', 'h'): 2258,
 ('h', '</E>'): 2318,
 ('i', 'r'): 816,
 ('r', '</E>'): 1232,
 ('b', 'r'): 750,
 ('r', 'i'): 2785,
 ('i', 'e'): 1546,
 ('e', 'l'): 3093,
 ('l', 'l'): 1273,
 ('l', 'a'): 2482,
 ('a', '</E>'): 6508,
 ('a', 'd'): 977,
 ('a', 'm'): 1512,
 ('m', '</E>'): 479,
 ('a', 'r'): 3030,
 ('r', 's'): 167,
 ('s', 'h'): 1230,
 ('a', 'y'): 1904,
 ('y', 'a'): 2088,
 ('d', 'e'): 1169,
 ('e', 'n'): 2417,
 ('d', 'h'): 116,
 ('h', 'a'): 2112,
 ('a', 'v'): 789,
 ('v', '</E>'): 86,
 ('v', 'a'): 614,
 ('h', 'i'): 704,
 ('i', '</E>'): 2233,
 ('r', 'a'): 2247,
 ('h', 'v'): 39,
 ('v', 'i'): 880,
 ('i', 'k'): 425,
 ('k', '</E>'): 356,
 ('k', 'a'): 1607,
 ('h', 'y'): 191,
 ('r', 'e'): 1553,
 ('e', 'd'): 363,
 ('d', 'd'): 138,
 ('d', 'y'): 268,
 ('y', '</E>'): 1737,
 ('a', 's'): 1053,
 ('s', 'r'): 55,
 ('d', '

In [9]:
sorted(b.items(), key = lambda kv: -kv[1])

[(('a', '</E>'), 6508),
 (('n', '</E>'), 6040),
 (('a', 'n'), 5120),
 (('<S>', 'a'), 4155),
 (('e', '</E>'), 3676),
 (('e', 'l'), 3093),
 (('a', 'r'), 3030),
 (('n', 'a'), 2923),
 (('r', 'i'), 2785),
 (('<S>', 'k'), 2700),
 (('l', 'e'), 2688),
 (('l', 'a'), 2482),
 (('m', 'a'), 2451),
 (('a', 'l'), 2431),
 (('e', 'n'), 2417),
 (('<S>', 'm'), 2401),
 (('l', 'i'), 2361),
 (('i', 'a'), 2347),
 (('h', '</E>'), 2318),
 (('a', 'h'), 2258),
 (('r', 'a'), 2247),
 (('<S>', 'j'), 2239),
 (('i', '</E>'), 2233),
 (('o', 'n'), 2213),
 (('h', 'a'), 2112),
 (('y', 'a'), 2088),
 (('i', 'n'), 1963),
 (('<S>', 's'), 1914),
 (('a', 'y'), 1904),
 (('n', 'n'), 1818),
 (('e', 'r'), 1772),
 (('y', '</E>'), 1737),
 (('y', 'n'), 1641),
 (('k', 'a'), 1607),
 (('n', 'i'), 1607),
 (('<S>', 'd'), 1579),
 (('r', 'e'), 1553),
 (('a', 'i'), 1552),
 (('i', 'e'), 1546),
 (('a', 'm'), 1512),
 (('l', 'y'), 1487),
 (('<S>', 'r'), 1471),
 (('<S>', 'l'), 1451),
 (('<S>', 'e'), 1435),
 (('<S>', 'c'), 1398),
 (('j', 'a'), 138

In [10]:
list(w)

['z', 'z', 'y', 'z', 'x']

In [11]:
w

'zzyzx'

In [12]:
w[1:]

'zyzx'

In [13]:
# storing the information in 2d array - rows = 1st charachter, columns = 2nd charachter
import torch

In [14]:
a = torch.zeros((3, 5), dtype = torch.int32)
a

tensor([[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]], dtype=torch.int32)

In [15]:
a.dtype

torch.int32

In [16]:
# changing bit in the array
a[1, 3] = 1
a

tensor([[0, 0, 0, 0, 0],
        [0, 0, 0, 1, 0],
        [0, 0, 0, 0, 0]], dtype=torch.int32)

In [17]:
N = torch.zeros((27, 27), dtype = torch.int32)

In [18]:
len(set(''.join(words)))

26

In [19]:
chars = sorted(list(set(''.join(words))))
stoi = {s:i+1 for i, s in enumerate(chars)}
stoi['.'] = 0
itos = {i:s for s, i in stoi.items()}

In [20]:
 # stoi

In [21]:
for w in words:
  chs = ['.'] + list(w) + ['.']
  for ch1, ch2 in zip(chs, chs[1:]):
    ix1 = stoi[ch1]
    ix2 = stoi[ch2]
    N[ix1, ix2] += 1

In [ ]:
import matplotlib.pyplot as plt
%matplotlib inline

plt.figure(figsize=(16, 16))
plt.imshow(N, cmap='Blues')

for i in range(27):
  for j in range(27):
    chstr = itos[i] + itos[j]
    plt.text(j, i, chstr, ha='center', va='bottom', color= 'gray')
    plt.text(j, i, N[i, j].item(), ha='center', va='top', color= 'gray')
plt.axis('off')
plt.tight_layout()
plt.show()

: 

In [22]:
N[0, :]

tensor([   0, 4155, 1153, 1398, 1579, 1435,  383,  620,  798,  553, 2239, 2700,
        1451, 2401, 1090,  358,  467,   85, 1471, 1914, 1209,   71,  363,  262,
         131,  519,  876], dtype=torch.int32)

In [23]:
# creating probability vector
p = N[0].float()
p = p / p.sum()
p

tensor([0.0000, 0.1400, 0.0388, 0.0471, 0.0532, 0.0483, 0.0129, 0.0209, 0.0269,
        0.0186, 0.0754, 0.0910, 0.0489, 0.0809, 0.0367, 0.0121, 0.0157, 0.0029,
        0.0496, 0.0645, 0.0407, 0.0024, 0.0122, 0.0088, 0.0044, 0.0175, 0.0295])

In [24]:
p.sum()

tensor(1.0000)

In [25]:
g = torch.Generator().manual_seed(2147483647)
ix = torch.multinomial(p, num_samples=1, replacement=True, generator=g).item()
itos[ix]

'j'

In [26]:
g = torch.Generator().manual_seed(2147483647)
p = torch.rand(3, generator=g)
p = p / p.sum()
p

tensor([0.6064, 0.3033, 0.0903])

In [27]:
torch.multinomial(p, num_samples=100, replacement=True, generator=g)

tensor([1, 1, 2, 0, 0, 2, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 2, 0, 0,
        1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1,
        0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
        0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 2, 0, 0, 0, 0, 0, 0, 1, 0, 0, 2, 0, 1, 0,
        0, 1, 1, 1])

In [28]:
p.shape

torch.Size([3])

In [32]:
P.shape

torch.Size([27, 27])

In [61]:
# 27, 27
# 27, 1

In [31]:
P.sum(1, keepdim=True).shape

torch.Size([27, 1])

In [30]:
P = (N+1).float()
P /= P.sum(1, keepdims=True)

In [33]:
P[:,0].sum()

tensor(2.9531)

### Note: Broadcasting Sementics from Pytorch or tutorials and practice 

In [34]:
g = torch.Generator().manual_seed(2147483647)

for i in range(5):

  out = []
  ix = 0
  while True:
    p = P[ix]
    # p = N[ix].float()
    # p = p / p.sum()
    # p = torch.ones(27) / 27.0
    ix = torch.multinomial(p, num_samples=1, replacement=True, generator=g).item()
    out.append(itos[ix])
    if ix == 0:
      break
  print(''.join(out))


junide.
janasah.
p.
cony.
a.


In [35]:
# log(a+b+c) = log(a) + log(b) + log(c)

In [36]:
# GOAL: maximize likelihood of the data w.r.t model parameters (statistical modeling)
# equivalent ot maximizing the log likelihood ( beacause log is the monotonic)
# equivalent to minimizing the negative log likelihood
# equivalent to minimizing the average negative log likelihood

# log(a*b*c) = log(a) + log(b) + log(c)

In [37]:
log_likelihood = 0.0
n = 0

for w in words:
# for w in ['ebadx']:
  chs = ['.'] + list(w) + ['.']
  for ch1, ch2 in zip(chs, chs[1:]):
    ix1 = stoi[ch1]
    ix2 = stoi[ch2]
    prob = P[ix1, ix2]
    logprob = torch.log(prob)
    log_likelihood += logprob
    n += 1
    # print(f'{ch1}{ch2}: {prob:.4f} {logprob:4f}') # probabilities model assigns to the bigrams

print(f'{log_likelihood=}')
nll = -log_likelihood
print(f'{nll=}') 
print(f'{nll/n=}') # average negative log likelihood

log_likelihood=tensor(-522205.6562)
nll=tensor(522205.6562)
nll/n=tensor(2.4548)


### Note: to see the literature of Maximum likelihood estimation
* WolframAlpha website for logs

In [38]:
# create the training set of all the bigrams (x,y)
xs, ys = [], []

for w in words[:1]:
  chs = ['.'] + list(w) + ['.']
  for ch1, ch2 in zip(chs, chs[1:]):
    ix1 = stoi[ch1]
    ix2 = stoi[ch2]
    print(ch1, ch2)
    xs.append(ix1)
    ys.append(ix2)

xs = torch.tensor(xs) 
ys = torch.tensor(ys)

. a
a a
a b
b a
a n
n .


In [39]:
xs

tensor([ 0,  1,  1,  2,  1, 14])

In [40]:
ys

tensor([ 1,  1,  2,  1, 14,  0])

In [41]:
# one hot encoding with PyTorch
import torch.nn.functional as F
xenc = F.one_hot(xs, num_classes=27).float() # casting this to float
xenc

tensor([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [42]:
xenc.shape

torch.Size([6, 27])

In [43]:
#import matplotlib.pyplot as plt
#%matplotlib inline
#plt.imshow(xenc.T, cmap='Blues')
# turned on bits are the bigrams

In [44]:
# data types have to be float for NN
xenc.dtype

torch.float32

In [127]:
W = torch.randn(27, 27)
xenc @ W # @ used for matrix multiplication in PyTorch

tensor([[-0.3332,  1.0716,  0.1085,  0.1040, -0.6817, -0.7600,  0.1348,  0.0653,
          0.8847,  0.7496, -1.0206, -0.4908, -0.5470, -0.6289, -0.3616,  0.4408,
          0.5945, -1.4407,  0.2931, -0.5711,  0.1083, -0.8254, -1.1108,  1.2223,
          0.0374, -1.4060,  2.0371],
        [ 0.0838, -0.7973,  0.0232, -0.7750, -0.2299,  0.2636, -0.8441,  0.0179,
          1.0942, -0.2748,  1.5213,  0.1811, -0.4153,  0.5469,  0.1684, -0.0772,
          0.5558, -0.2036, -0.1618,  0.7381, -0.8191,  0.9044,  0.3088, -1.0977,
         -0.1128,  1.2148,  0.4995],
        [ 0.0838, -0.7973,  0.0232, -0.7750, -0.2299,  0.2636, -0.8441,  0.0179,
          1.0942, -0.2748,  1.5213,  0.1811, -0.4153,  0.5469,  0.1684, -0.0772,
          0.5558, -0.2036, -0.1618,  0.7381, -0.8191,  0.9044,  0.3088, -1.0977,
         -0.1128,  1.2148,  0.4995],
        [-0.1689,  1.1564, -0.2120,  0.6238, -0.9548,  0.4504, -0.1378, -0.6064,
          1.1054,  0.1802, -0.5261, -0.4971,  1.0251,  0.6337, -0.4048,  0.3829

In [128]:
(xenc @ W).shape

torch.Size([6, 27])

In [129]:
(xenc @ W)[3, 13] # firing rate for the 13th neuron when the input is the 3rd neuron

tensor(0.6337)

In [130]:
logits = xenc @ W # log-counts
counts = logits.exp() # all the negative values are converted to positive values by using exp and all the positive values are increased. Equivalent to the N matrix.
probs = counts / counts.sum(1, keepdims=True) # probabilities
probs

tensor([[0.0199, 0.0809, 0.0309, 0.0307, 0.0140, 0.0130, 0.0317, 0.0296, 0.0671,
         0.0586, 0.0100, 0.0170, 0.0160, 0.0148, 0.0193, 0.0430, 0.0502, 0.0066,
         0.0371, 0.0156, 0.0309, 0.0121, 0.0091, 0.0940, 0.0288, 0.0068, 0.2124],
        [0.0297, 0.0123, 0.0280, 0.0126, 0.0217, 0.0356, 0.0117, 0.0278, 0.0816,
         0.0208, 0.1251, 0.0327, 0.0180, 0.0472, 0.0323, 0.0253, 0.0476, 0.0223,
         0.0232, 0.0572, 0.0120, 0.0675, 0.0372, 0.0091, 0.0244, 0.0921, 0.0450],
        [0.0297, 0.0123, 0.0280, 0.0126, 0.0217, 0.0356, 0.0117, 0.0278, 0.0816,
         0.0208, 0.1251, 0.0327, 0.0180, 0.0472, 0.0323, 0.0253, 0.0476, 0.0223,
         0.0232, 0.0572, 0.0120, 0.0675, 0.0372, 0.0091, 0.0244, 0.0921, 0.0450],
        [0.0201, 0.0758, 0.0193, 0.0445, 0.0092, 0.0374, 0.0208, 0.0130, 0.0720,
         0.0286, 0.0141, 0.0145, 0.0665, 0.0449, 0.0159, 0.0350, 0.0118, 0.0407,
         0.0134, 0.0032, 0.0234, 0.0398, 0.0246, 0.0074, 0.2527, 0.0131, 0.0385],
        [0.0297, 0.0123,

In [131]:
probs[0]

tensor([0.0199, 0.0809, 0.0309, 0.0307, 0.0140, 0.0130, 0.0317, 0.0296, 0.0671,
        0.0586, 0.0100, 0.0170, 0.0160, 0.0148, 0.0193, 0.0430, 0.0502, 0.0066,
        0.0371, 0.0156, 0.0309, 0.0121, 0.0091, 0.0940, 0.0288, 0.0068, 0.2124])

In [132]:
probs.shape

torch.Size([6, 27])

In [133]:
probs[0].sum()

tensor(1.0000)

In [134]:
xenc[3]

tensor([0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [135]:
W[:, 13]

tensor([-0.6289,  0.5469,  0.6337, -1.4847,  0.7977, -0.4745,  0.2883,  2.3038,
         0.4826,  1.2167,  0.1630, -0.6329,  0.8956,  1.4039, -1.3861, -0.1797,
         1.0911, -0.2216,  1.9568,  0.0128, -0.1016, -0.2015,  0.4741, -0.7818,
         0.9654,  0.6171,  0.3163])

In [136]:
(xenc[3] * W[:, 13]).sum() # Wx dot product

tensor(0.6337)

In [137]:
# Summary
xs

tensor([ 0,  1,  1,  2,  1, 14])

In [138]:
ys

tensor([ 1,  1,  2,  1, 14,  0])

In [139]:
# randomly initialized 27 neurons weights. Each neuron receives 27 inputs
g = torch.Generator().manual_seed(2147483647)
W = torch.randn(27, 27, generator=g) # weights

In [140]:
# Forward pass
xenc = F.one_hot(xs, num_classes=27).float() # one hot encoding of the inputs
logits = xenc @ W # predict log-counts
counts = logits.exp() # counts equivalent to N matrix
probs = counts / counts.sum(1, keepdims=True) # probabilities for next character
# The last 2  lines together are called softmax function

In [141]:
probs.shape

torch.Size([6, 27])

In [161]:

nlls = torch.zeros(5)
for i in range(5):
  # i-th bigram:
  x = xs[i].item() # input character index
  y = ys[i].item() # label character index
  print('----------------------')
  print(f'bigram example {i+1}: {itos[x]}{itos[y]} (indexes: {x}, {y})')
  print('input to the neural network:', probs[i])
  print('output probabilities from the neural network:', probs[i])
  print('label (actual next character):', y)
  p = probs[i, y]
  print( 'probability assigned by the network to the correct character:', p.item())
  logp = torch.log(p)
  print('log likelihood:', logp.item())
  nll = logp
  print('negative log likelihood:', nll.item())
  nlls[i] = nll

  print('=======================')
  print('average negative log likelihood, i.e loss =', nlls.mean().item())

----------------------
bigram example 1: .a (indexes: 0, 1)
input to the neural network: tensor([0.0607, 0.0100, 0.0123, 0.0042, 0.0168, 0.0123, 0.0027, 0.0232, 0.0137,
        0.0313, 0.0079, 0.0278, 0.0091, 0.0082, 0.0500, 0.2378, 0.0603, 0.0025,
        0.0249, 0.0055, 0.0339, 0.0109, 0.0029, 0.0198, 0.0118, 0.1537, 0.1459])
output probabilities from the neural network: tensor([0.0607, 0.0100, 0.0123, 0.0042, 0.0168, 0.0123, 0.0027, 0.0232, 0.0137,
        0.0313, 0.0079, 0.0278, 0.0091, 0.0082, 0.0500, 0.2378, 0.0603, 0.0025,
        0.0249, 0.0055, 0.0339, 0.0109, 0.0029, 0.0198, 0.0118, 0.1537, 0.1459])
label (actual next character): 1
probability assigned by the network to the correct character: 0.009982486255466938
log likelihood: -4.6069231033325195
negative log likelihood: -4.6069231033325195
average negative log likelihood, i.e loss = -0.9213846325874329
----------------------
bigram example 2: aa (indexes: 1, 1)
input to the neural network: tensor([0.0150, 0.0086, 0.0396, 0

In [167]:
# ----------- optimization ----------------

In [168]:
xs

tensor([ 0,  1,  1,  2,  1, 14])

In [169]:
ys

tensor([ 1,  1,  2,  1, 14,  0])

In [170]:
# randomly initialized 27 neurons weights. Each neuron receives 27 inputs
g = torch.Generator().manual_seed(2147483647)
W = torch.randn(27, 27, generator=g, requires_grad=True) # weights

In [196]:
# Forward pass
xenc = F.one_hot(xs, num_classes=27).float() # one hot encoding of the inputs
logits = xenc @ W # predict log-counts
counts = logits.exp() # counts equivalent to N matrix
probs = counts / counts.sum(1, keepdims=True) # probabilities for next character
loss = -probs[torch.arange(6), ys].log().mean() # negative log likelihood

In [172]:
probs.shape

torch.Size([6, 27])

In [173]:
#probs[0, 1], probs[1, 1], probs[2, 2], probs[3, 1], probs[4, 14], probs[5, 0]

In [174]:
#torch.arange(6) # with pytorch

In [175]:
# in Pytorch
#loss = -probs[torch.arange(6), ys].log().mean()
#loss

In [194]:
# Backward Pass in Pytorch
W.grad = None # setting the gradients to zero
loss.backward() # backpropagation

In [182]:
# W.grad.shape

In [183]:
# W.grad

In [197]:
print(loss.item()) # loss getting smaller by the backward, update and forward pass

3.791404962539673


In [195]:
# Updating the tensor
W.data += -0.1 * W.grad

In [198]:
# ---------------------Rearranging the code--------------------

In [204]:
# Create the dataset
xs, ys = [], []
for w in words: #[:1] # optimizing the entire training set
  chs = ['.'] + list(w) + ['.']
  for ch1, ch2 in zip(chs, chs[1:]):
    ix1 = stoi[ch1]
    ix2 = stoi[ch2]
    xs.append(ix1)
    ys.append(ix2)
xs = torch.tensor(xs)
ys = torch.tensor(ys)
num = xs.nelement()
print('number of examples:', num)

# initialize the 'networs'
g = torch.Generator().manual_seed(2147483647)
W = torch.randn(27, 27, generator=g, requires_grad=True)

number of examples: 212725


In [ ]:
# gradient descent
for k in range(100): # iterations

  # Forward pass
  xenc = F.one_hot(xs, num_classes=27).float() # one hot encoding of the inputs
  logits = xenc @ W # predict log-counts
  counts = logits.exp() # counts equivalent to N matrix
  probs = counts / counts.sum(1, keepdims=True) # probabilities for next character
  loss = -probs[torch.arange(num), ys].log().mean() # negative log likelihood
  print(loss.item())

  # Backward pass
  W.grad = None # setting the gradients to zero
  loss.backward() # backpropagation

  # Update
  W.data += -50 * W.grad

  # entire training set is optimized in one go (achieveing the same result as the goal)

2.46226167678833
2.4622151851654053
2.4621694087982178
2.4621241092681885
2.4620792865753174
2.4620349407196045
2.4619908332824707
2.4619476795196533
2.4619040489196777
2.461862087249756
2.461819887161255
2.461778163909912
2.4617369174957275
2.461696147918701
2.461655855178833
2.461616039276123
2.461576223373413
2.4615371227264404
2.461498498916626
2.4614598751068115
2.4614217281341553
2.4613840579986572
2.4613468647003174
2.4613096714019775
2.461273431777954
2.4612371921539307
2.4612011909484863
2.4611656665802
2.461130380630493
2.4610955715179443
2.4610610008239746
2.461026668548584
2.4609928131103516
2.4609594345092773
2.460926055908203
2.460893154144287
2.46086049079895
2.4608280658721924
2.4607958793640137
2.460763931274414
2.4607326984405518
2.4607014656066895
2.4606704711914062
2.460639715194702
2.4606094360351562
2.4605791568756104
2.4605493545532227
2.460519552230835
2.4604902267456055
2.460461139678955
2.4604320526123047
2.4604034423828125
2.4603753089904785
2.460346937179565